### ISSUE TITLE
404s on the kernels section of the website

### ISSUE THREAD

**Issue by cvaske** [nteract/nteract.io#197] opened 2019-08-19 20:11 UTC
![Untitled](https://user-images.githubusercontent.com/100392/63295948-c64d4300-c282-11e9-8143-0eb60938200c.gif)

**Comment by captainsafia** [comment] 2019-08-20 02:19
Closing as this is a dupe of #195 

I believe this might a result of our recent changes to the Now deployment.

**Closed by captainsafia** 2019-08-20 02:19 UTC
